import {notFound, redirect} from "next/navigation";
// importing "not-found" from 'next/navigation', which can be also used to render a custom not-found page corresponding to a trigger

function getRandomInt(count: number) {
    return Math.floor(Math.random() * count);
}
// this is a standard JavaScript function that generates a random integer between 0 and the specified count (exclusive). It uses Math.random() to generate a random number between 0 (inclusive) and 1 (exclusive), multiplies it by the count, and then uses Math.floor() to round it down to the nearest integer.

export default async function ProductReview({
    params,
}: {
    params: Promise<{ productId: string, reviewId: string}>;
})
{
    const random =  getRandomInt(2);
    if(random == 1) {
        throw new Error("Error loading review");
    }
    // this is a standard JavaScript conditional statement that checks if the random integer generated by the getRandomInt function is equal to 1. If it is, it throws an error with the message "Error loading review". This simulates a scenario where an error occurs while loading a product review, which can be useful for testing error handling in the application.
    const {productId, reviewId} = await params;
    // this is a standard JavaScript object destucturing. It takes the resolved object and instantly *"unpacks"*the **productId** and **reviewId** properties into their own standalone variables.
    if(parseInt(reviewId) > 1000) {
        // notFound();
        redirect("/products");
        // instead of rendering a not-found page, we redirect the user to the 'products' page
    }
    // trigger - if reviewId is greater than 1000
    return <h1>Details about product {productId} and review {reviewId}</h1>;
}